name: telegram message
on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

jobs:
  bot:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "scheduled event: ${{ github.event.schedule }}"
