name: telegram message
on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "this is a test message. Please work :))))"
