name: telegram message
on:
  push:
    schedule:
      - cron: "30 5 * * 1,3"
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "scheduled event: ${{github.event.schedule}}"
