name: telegram message
on:
  push:
    schedule:
      - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *" # shortest workflow is every 5 minutes

jobs:
  bot:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "scheduled event: ${{ github.event.schedule }}"
